# Generated by Django 5.2 on 2025-04-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0002_video_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hashtag',
            new_name='hashteg',
        ),
    ]
