# Generated by Django 5.2 on 2025-05-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0003_rename_hashtag_video_hashteg'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
