# Generated by Django 5.2 on 2025-05-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0005_remove_video_viewed_videoview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoview',
            options={'ordering': ['-viewed_at']},
        ),
    ]
